### PR TITLE
Feature/upload download csv

### PR DESCRIPTION
**Pull request by jesusvilartoptal**

### CODE REVIEW

**Comment by iskrisis** [comment]
Why did you close this?

**Comment by jesusvilartoptal** [comment]
It wasn't ready yet.

CSV parsing was buggy, so I'm working at the moment on a version that uses Papaparse.

Will reopen again soon if you think it could be a good addition.

**Comment by iskrisis** [comment]
I think it might be but the plugin is well in not great shape. I hacked this and published it without too much thought. After some users started to use it Kirby 3 started to happen (and panel is completely new) so i am actually determined to make the field better for Kirby 3 but not 2. Kirby 3 is around the corner.

So if you want to make it go for it and we might adapt that for Kirby 3.

**Comment by iskrisis** [comment]
Yea and if you use it any ideas for new version features are appreciated. Post new issues for features pls.

Cheers

**Comment by jesusvilartoptal** [comment]
Sure, will do.

FYI, just opened #13 that uses Papaparse

**Pull request closed without merging**
